/* 
 * SCILL API
 *
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SCILL.Api;
using SCILL.Model;
using SCILL.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SCILL.Test
{
    /// <summary>
    ///  Class for testing AccessToken
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AccessTokenTests
    {
        // TODO uncomment below to declare an instance variable for AccessToken
        //private AccessToken instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AccessToken
            //instance = new AccessToken();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AccessToken
        /// </summary>
        [Test]
        public void AccessTokenInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AccessToken
            //Assert.IsInstanceOfType<AccessToken> (instance, "variable 'instance' is a AccessToken");
        }


        /// <summary>
        /// Test the property 'token'
        /// </summary>
        [Test]
        public void tokenTest()
        {
            // TODO unit test for the property 'token'
        }

    }

}
