/* 
 * SCILL API
 *
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.2.0
 * Contact: support@scillgame.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SCILL.Api;
using SCILL.Model;
using SCILL.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SCILL.Test
{
    /// <summary>
    ///  Class for testing ActionResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ActionResponseTests
    {
        // TODO uncomment below to declare an instance variable for ActionResponse
        //private ActionResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ActionResponse
            //instance = new ActionResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ActionResponse
        /// </summary>
        [Test]
        public void ActionResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ActionResponse
            //Assert.IsInstanceOfType<ActionResponse> (instance, "variable 'instance' is a ActionResponse");
        }


        /// <summary>
        /// Test the property 'status'
        /// </summary>
        [Test]
        public void statusTest()
        {
            // TODO unit test for the property 'status'
        }
        /// <summary>
        /// Test the property 'message'
        /// </summary>
        [Test]
        public void messageTest()
        {
            // TODO unit test for the property 'message'
        }
        /// <summary>
        /// Test the property 'challenge'
        /// </summary>
        [Test]
        public void challengeTest()
        {
            // TODO unit test for the property 'challenge'
        }

    }

}
