/* 
 * SCILL API
 *
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.2.0
 * Contact: support@scillgame.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SCILL.Api;
using SCILL.Model;
using SCILL.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SCILL.Test
{
    /// <summary>
    ///  Class for testing BattlePassTranslation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BattlePassTranslationTests
    {
        // TODO uncomment below to declare an instance variable for BattlePassTranslation
        //private BattlePassTranslation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BattlePassTranslation
            //instance = new BattlePassTranslation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BattlePassTranslation
        /// </summary>
        [Test]
        public void BattlePassTranslationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BattlePassTranslation
            //Assert.IsInstanceOfType<BattlePassTranslation> (instance, "variable 'instance' is a BattlePassTranslation");
        }


        /// <summary>
        /// Test the property 'language_id'
        /// </summary>
        [Test]
        public void language_idTest()
        {
            // TODO unit test for the property 'language_id'
        }
        /// <summary>
        /// Test the property 'name'
        /// </summary>
        [Test]
        public void nameTest()
        {
            // TODO unit test for the property 'name'
        }
        /// <summary>
        /// Test the property 'description'
        /// </summary>
        [Test]
        public void descriptionTest()
        {
            // TODO unit test for the property 'description'
        }
        /// <summary>
        /// Test the property 'short_description'
        /// </summary>
        [Test]
        public void short_descriptionTest()
        {
            // TODO unit test for the property 'short_description'
        }
        /// <summary>
        /// Test the property 'disclaimer'
        /// </summary>
        [Test]
        public void disclaimerTest()
        {
            // TODO unit test for the property 'disclaimer'
        }

    }

}
