/* 
 * SCILL API
 *
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.2.0
 * Contact: support@scillgame.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SCILL.Api;
using SCILL.Model;
using SCILL.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SCILL.Test
{
    /// <summary>
    ///  Class for testing BattlePassChallengeState
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BattlePassChallengeStateTests
    {
        // TODO uncomment below to declare an instance variable for BattlePassChallengeState
        //private BattlePassChallengeState instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BattlePassChallengeState
            //instance = new BattlePassChallengeState();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BattlePassChallengeState
        /// </summary>
        [Test]
        public void BattlePassChallengeStateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BattlePassChallengeState
            //Assert.IsInstanceOfType<BattlePassChallengeState> (instance, "variable 'instance' is a BattlePassChallengeState");
        }


        /// <summary>
        /// Test the property 'app_id'
        /// </summary>
        [Test]
        public void app_idTest()
        {
            // TODO unit test for the property 'app_id'
        }
        /// <summary>
        /// Test the property 'battle_pass_id'
        /// </summary>
        [Test]
        public void battle_pass_idTest()
        {
            // TODO unit test for the property 'battle_pass_id'
        }
        /// <summary>
        /// Test the property 'level_id'
        /// </summary>
        [Test]
        public void level_idTest()
        {
            // TODO unit test for the property 'level_id'
        }
        /// <summary>
        /// Test the property 'user_id'
        /// </summary>
        [Test]
        public void user_idTest()
        {
            // TODO unit test for the property 'user_id'
        }
        /// <summary>
        /// Test the property 'level_position_index'
        /// </summary>
        [Test]
        public void level_position_indexTest()
        {
            // TODO unit test for the property 'level_position_index'
        }
        /// <summary>
        /// Test the property 'challenge_id'
        /// </summary>
        [Test]
        public void challenge_idTest()
        {
            // TODO unit test for the property 'challenge_id'
        }
        /// <summary>
        /// Test the property 'challenge_position_index'
        /// </summary>
        [Test]
        public void challenge_position_indexTest()
        {
            // TODO unit test for the property 'challenge_position_index'
        }
        /// <summary>
        /// Test the property 'challenge_goal'
        /// </summary>
        [Test]
        public void challenge_goalTest()
        {
            // TODO unit test for the property 'challenge_goal'
        }
        /// <summary>
        /// Test the property 'user_challenge_current_score'
        /// </summary>
        [Test]
        public void user_challenge_current_scoreTest()
        {
            // TODO unit test for the property 'user_challenge_current_score'
        }
        /// <summary>
        /// Test the property 'type'
        /// </summary>
        [Test]
        public void typeTest()
        {
            // TODO unit test for the property 'type'
        }

    }

}
