/* 
 * SCILL API
 *
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.2.0
 * Contact: support@scillgame.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SCILL.Api;
using SCILL.Model;
using SCILL.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SCILL.Test
{
    /// <summary>
    ///  Class for testing BattlePassLevelReward
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BattlePassLevelRewardTests
    {
        // TODO uncomment below to declare an instance variable for BattlePassLevelReward
        //private BattlePassLevelReward instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BattlePassLevelReward
            //instance = new BattlePassLevelReward();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BattlePassLevelReward
        /// </summary>
        [Test]
        public void BattlePassLevelRewardInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BattlePassLevelReward
            //Assert.IsInstanceOfType<BattlePassLevelReward> (instance, "variable 'instance' is a BattlePassLevelReward");
        }


        /// <summary>
        /// Test the property 'app_id'
        /// </summary>
        [Test]
        public void app_idTest()
        {
            // TODO unit test for the property 'app_id'
        }
        /// <summary>
        /// Test the property 'battle_pass_id'
        /// </summary>
        [Test]
        public void battle_pass_idTest()
        {
            // TODO unit test for the property 'battle_pass_id'
        }
        /// <summary>
        /// Test the property 'level_id'
        /// </summary>
        [Test]
        public void level_idTest()
        {
            // TODO unit test for the property 'level_id'
        }
        /// <summary>
        /// Test the property 'user_id'
        /// </summary>
        [Test]
        public void user_idTest()
        {
            // TODO unit test for the property 'user_id'
        }
        /// <summary>
        /// Test the property 'level_position_index'
        /// </summary>
        [Test]
        public void level_position_indexTest()
        {
            // TODO unit test for the property 'level_position_index'
        }
        /// <summary>
        /// Test the property 'reward_amount'
        /// </summary>
        [Test]
        public void reward_amountTest()
        {
            // TODO unit test for the property 'reward_amount'
        }
        /// <summary>
        /// Test the property 'reward_type_name'
        /// </summary>
        [Test]
        public void reward_type_nameTest()
        {
            // TODO unit test for the property 'reward_type_name'
        }

    }

}
