/* 
 * SCILL API
 *
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.2.0
 * Contact: support@scillgame.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SCILL.Api;
using SCILL.Model;
using SCILL.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SCILL.Test
{
    /// <summary>
    ///  Class for testing BattlePassState
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BattlePassStateTests
    {
        // TODO uncomment below to declare an instance variable for BattlePassState
        //private BattlePassState instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BattlePassState
            //instance = new BattlePassState();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BattlePassState
        /// </summary>
        [Test]
        public void BattlePassStateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BattlePassState
            //Assert.IsInstanceOfType<BattlePassState> (instance, "variable 'instance' is a BattlePassState");
        }


        /// <summary>
        /// Test the property 'battle_pass_id'
        /// </summary>
        [Test]
        public void battle_pass_idTest()
        {
            // TODO unit test for the property 'battle_pass_id'
        }
        /// <summary>
        /// Test the property 'app_id'
        /// </summary>
        [Test]
        public void app_idTest()
        {
            // TODO unit test for the property 'app_id'
        }
        /// <summary>
        /// Test the property 'battle_pass_priority'
        /// </summary>
        [Test]
        public void battle_pass_priorityTest()
        {
            // TODO unit test for the property 'battle_pass_priority'
        }
        /// <summary>
        /// Test the property 'start_date'
        /// </summary>
        [Test]
        public void start_dateTest()
        {
            // TODO unit test for the property 'start_date'
        }
        /// <summary>
        /// Test the property 'end_date'
        /// </summary>
        [Test]
        public void end_dateTest()
        {
            // TODO unit test for the property 'end_date'
        }
        /// <summary>
        /// Test the property 'is_active'
        /// </summary>
        [Test]
        public void is_activeTest()
        {
            // TODO unit test for the property 'is_active'
        }

    }

}
