/* 
 * SCILL API
 *
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SCILL.Api;
using SCILL.Model;
using SCILL.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SCILL.Test
{
    /// <summary>
    ///  Class for testing BattlePassLevel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BattlePassLevelTests
    {
        // TODO uncomment below to declare an instance variable for BattlePassLevel
        //private BattlePassLevel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BattlePassLevel
            //instance = new BattlePassLevel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BattlePassLevel
        /// </summary>
        [Test]
        public void BattlePassLevelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BattlePassLevel
            //Assert.IsInstanceOfType<BattlePassLevel> (instance, "variable 'instance' is a BattlePassLevel");
        }


        /// <summary>
        /// Test the property 'level_id'
        /// </summary>
        [Test]
        public void level_idTest()
        {
            // TODO unit test for the property 'level_id'
        }
        /// <summary>
        /// Test the property 'app_id'
        /// </summary>
        [Test]
        public void app_idTest()
        {
            // TODO unit test for the property 'app_id'
        }
        /// <summary>
        /// Test the property 'battle_pass_id'
        /// </summary>
        [Test]
        public void battle_pass_idTest()
        {
            // TODO unit test for the property 'battle_pass_id'
        }
        /// <summary>
        /// Test the property 'reward_amount'
        /// </summary>
        [Test]
        public void reward_amountTest()
        {
            // TODO unit test for the property 'reward_amount'
        }
        /// <summary>
        /// Test the property 'reward_type_name'
        /// </summary>
        [Test]
        public void reward_type_nameTest()
        {
            // TODO unit test for the property 'reward_type_name'
        }
        /// <summary>
        /// Test the property 'level_reward_type'
        /// </summary>
        [Test]
        public void level_reward_typeTest()
        {
            // TODO unit test for the property 'level_reward_type'
        }
        /// <summary>
        /// Test the property 'level_completed'
        /// </summary>
        [Test]
        public void level_completedTest()
        {
            // TODO unit test for the property 'level_completed'
        }
        /// <summary>
        /// Test the property 'level_priority'
        /// </summary>
        [Test]
        public void level_priorityTest()
        {
            // TODO unit test for the property 'level_priority'
        }
        /// <summary>
        /// Test the property 'reward_claimed'
        /// </summary>
        [Test]
        public void reward_claimedTest()
        {
            // TODO unit test for the property 'reward_claimed'
        }
        /// <summary>
        /// Test the property 'activated_at'
        /// </summary>
        [Test]
        public void activated_atTest()
        {
            // TODO unit test for the property 'activated_at'
        }
        /// <summary>
        /// Test the property 'challenges'
        /// </summary>
        [Test]
        public void challengesTest()
        {
            // TODO unit test for the property 'challenges'
        }

    }

}
