/* 
 * SCILL API
 *
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.2.0
 * Contact: support@scillgame.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SCILL.Api;
using SCILL.Model;
using SCILL.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SCILL.Test
{
    /// <summary>
    ///  Class for testing BattlePassLevelClaimedPayload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BattlePassLevelClaimedPayloadTests
    {
        // TODO uncomment below to declare an instance variable for BattlePassLevelClaimedPayload
        //private BattlePassLevelClaimedPayload instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BattlePassLevelClaimedPayload
            //instance = new BattlePassLevelClaimedPayload();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BattlePassLevelClaimedPayload
        /// </summary>
        [Test]
        public void BattlePassLevelClaimedPayloadInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BattlePassLevelClaimedPayload
            //Assert.IsInstanceOfType<BattlePassLevelClaimedPayload> (instance, "variable 'instance' is a BattlePassLevelClaimedPayload");
        }


        /// <summary>
        /// Test the property 'webhook_type'
        /// </summary>
        [Test]
        public void webhook_typeTest()
        {
            // TODO unit test for the property 'webhook_type'
        }
        /// <summary>
        /// Test the property 'battle_pass_level_reward_claimed'
        /// </summary>
        [Test]
        public void battle_pass_level_reward_claimedTest()
        {
            // TODO unit test for the property 'battle_pass_level_reward_claimed'
        }

    }

}
