/* 
 * SCILL API
 *
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.2.0
 * Contact: support@scillgame.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SCILL.Api;
using SCILL.Model;
using SCILL.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SCILL.Test
{
    /// <summary>
    ///  Class for testing BattlePassUnlockPayload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BattlePassUnlockPayloadTests
    {
        // TODO uncomment below to declare an instance variable for BattlePassUnlockPayload
        //private BattlePassUnlockPayload instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BattlePassUnlockPayload
            //instance = new BattlePassUnlockPayload();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BattlePassUnlockPayload
        /// </summary>
        [Test]
        public void BattlePassUnlockPayloadInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BattlePassUnlockPayload
            //Assert.IsInstanceOfType<BattlePassUnlockPayload> (instance, "variable 'instance' is a BattlePassUnlockPayload");
        }


        /// <summary>
        /// Test the property 'purchase_price'
        /// </summary>
        [Test]
        public void purchase_priceTest()
        {
            // TODO unit test for the property 'purchase_price'
        }
        /// <summary>
        /// Test the property 'purchase_currency'
        /// </summary>
        [Test]
        public void purchase_currencyTest()
        {
            // TODO unit test for the property 'purchase_currency'
        }

    }

}
