/* 
 * SCILL API
 *
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SCILL.Api;
using SCILL.Model;
using SCILL.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SCILL.Test
{
    /// <summary>
    ///  Class for testing Challenge
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ChallengeTests
    {
        // TODO uncomment below to declare an instance variable for Challenge
        //private Challenge instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Challenge
            //instance = new Challenge();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Challenge
        /// </summary>
        [Test]
        public void ChallengeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Challenge
            //Assert.IsInstanceOfType<Challenge> (instance, "variable 'instance' is a Challenge");
        }


        /// <summary>
        /// Test the property 'challenge_id'
        /// </summary>
        [Test]
        public void challenge_idTest()
        {
            // TODO unit test for the property 'challenge_id'
        }
        /// <summary>
        /// Test the property 'challenge_name'
        /// </summary>
        [Test]
        public void challenge_nameTest()
        {
            // TODO unit test for the property 'challenge_name'
        }
        /// <summary>
        /// Test the property 'challenge_description'
        /// </summary>
        [Test]
        public void challenge_descriptionTest()
        {
            // TODO unit test for the property 'challenge_description'
        }
        /// <summary>
        /// Test the property 'challenge_duration_time'
        /// </summary>
        [Test]
        public void challenge_duration_timeTest()
        {
            // TODO unit test for the property 'challenge_duration_time'
        }
        /// <summary>
        /// Test the property 'live_date'
        /// </summary>
        [Test]
        public void live_dateTest()
        {
            // TODO unit test for the property 'live_date'
        }
        /// <summary>
        /// Test the property 'challenge_goal'
        /// </summary>
        [Test]
        public void challenge_goalTest()
        {
            // TODO unit test for the property 'challenge_goal'
        }
        /// <summary>
        /// Test the property 'user_challenge_current_score'
        /// </summary>
        [Test]
        public void user_challenge_current_scoreTest()
        {
            // TODO unit test for the property 'user_challenge_current_score'
        }
        /// <summary>
        /// Test the property 'challenge_icon'
        /// </summary>
        [Test]
        public void challenge_iconTest()
        {
            // TODO unit test for the property 'challenge_icon'
        }
        /// <summary>
        /// Test the property 'challenge_icon_hd'
        /// </summary>
        [Test]
        public void challenge_icon_hdTest()
        {
            // TODO unit test for the property 'challenge_icon_hd'
        }
        /// <summary>
        /// Test the property 'challenge_price'
        /// </summary>
        [Test]
        public void challenge_priceTest()
        {
            // TODO unit test for the property 'challenge_price'
        }
        /// <summary>
        /// Test the property 'challenge_reward'
        /// </summary>
        [Test]
        public void challenge_rewardTest()
        {
            // TODO unit test for the property 'challenge_reward'
        }
        /// <summary>
        /// Test the property 'challenge_reward_type'
        /// </summary>
        [Test]
        public void challenge_reward_typeTest()
        {
            // TODO unit test for the property 'challenge_reward_type'
        }
        /// <summary>
        /// Test the property 'challenge_goal_condition'
        /// </summary>
        [Test]
        public void challenge_goal_conditionTest()
        {
            // TODO unit test for the property 'challenge_goal_condition'
        }
        /// <summary>
        /// Test the property 'challenge_xp'
        /// </summary>
        [Test]
        public void challenge_xpTest()
        {
            // TODO unit test for the property 'challenge_xp'
        }
        /// <summary>
        /// Test the property 'repeatable'
        /// </summary>
        [Test]
        public void repeatableTest()
        {
            // TODO unit test for the property 'repeatable'
        }
        /// <summary>
        /// Test the property 'type'
        /// </summary>
        [Test]
        public void typeTest()
        {
            // TODO unit test for the property 'type'
        }
        /// <summary>
        /// Test the property 'challenge_auto_activated'
        /// </summary>
        [Test]
        public void challenge_auto_activatedTest()
        {
            // TODO unit test for the property 'challenge_auto_activated'
        }
        /// <summary>
        /// Test the property 'is_claimed'
        /// </summary>
        [Test]
        public void is_claimedTest()
        {
            // TODO unit test for the property 'is_claimed'
        }
        /// <summary>
        /// Test the property 'user_challenge_unlocked_at'
        /// </summary>
        [Test]
        public void user_challenge_unlocked_atTest()
        {
            // TODO unit test for the property 'user_challenge_unlocked_at'
        }
        /// <summary>
        /// Test the property 'user_challenge_activated_at'
        /// </summary>
        [Test]
        public void user_challenge_activated_atTest()
        {
            // TODO unit test for the property 'user_challenge_activated_at'
        }
        /// <summary>
        /// Test the property 'user_challenge_is_claimed'
        /// </summary>
        [Test]
        public void user_challenge_is_claimedTest()
        {
            // TODO unit test for the property 'user_challenge_is_claimed'
        }
        /// <summary>
        /// Test the property 'user_challenge_status'
        /// </summary>
        [Test]
        public void user_challenge_statusTest()
        {
            // TODO unit test for the property 'user_challenge_status'
        }

    }

}
