/* 
 * SCILL API
 *
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SCILL.Api;
using SCILL.Model;
using SCILL.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SCILL.Test
{
    /// <summary>
    ///  Class for testing Leaderboard
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LeaderboardTests
    {
        // TODO uncomment below to declare an instance variable for Leaderboard
        //private Leaderboard instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Leaderboard
            //instance = new Leaderboard();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Leaderboard
        /// </summary>
        [Test]
        public void LeaderboardInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Leaderboard
            //Assert.IsInstanceOfType<Leaderboard> (instance, "variable 'instance' is a Leaderboard");
        }


        /// <summary>
        /// Test the property 'leaderboard_id'
        /// </summary>
        [Test]
        public void leaderboard_idTest()
        {
            // TODO unit test for the property 'leaderboard_id'
        }
        /// <summary>
        /// Test the property 'name'
        /// </summary>
        [Test]
        public void nameTest()
        {
            // TODO unit test for the property 'name'
        }
        /// <summary>
        /// Test the property 'grouped_by_users'
        /// </summary>
        [Test]
        public void grouped_by_usersTest()
        {
            // TODO unit test for the property 'grouped_by_users'
        }
        /// <summary>
        /// Test the property 'grouped_by_teams'
        /// </summary>
        [Test]
        public void grouped_by_teamsTest()
        {
            // TODO unit test for the property 'grouped_by_teams'
        }
        /// <summary>
        /// Test the property 'num_teams'
        /// </summary>
        [Test]
        public void num_teamsTest()
        {
            // TODO unit test for the property 'num_teams'
        }
        /// <summary>
        /// Test the property 'num_users'
        /// </summary>
        [Test]
        public void num_usersTest()
        {
            // TODO unit test for the property 'num_users'
        }

    }

}
