/* 
 * SCILL API
 *
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.2.0
 * Contact: support@scillgame.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SCILL.Api;
using SCILL.Model;
using SCILL.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SCILL.Test
{
    /// <summary>
    ///  Class for testing LeaderboardChanged
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LeaderboardChangedTests
    {
        // TODO uncomment below to declare an instance variable for LeaderboardChanged
        //private LeaderboardChanged instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LeaderboardChanged
            //instance = new LeaderboardChanged();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LeaderboardChanged
        /// </summary>
        [Test]
        public void LeaderboardChangedInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LeaderboardChanged
            //Assert.IsInstanceOfType<LeaderboardChanged> (instance, "variable 'instance' is a LeaderboardChanged");
        }


        /// <summary>
        /// Test the property 'webhook_type'
        /// </summary>
        [Test]
        public void webhook_typeTest()
        {
            // TODO unit test for the property 'webhook_type'
        }
        /// <summary>
        /// Test the property 'old_leaderboard'
        /// </summary>
        [Test]
        public void old_leaderboardTest()
        {
            // TODO unit test for the property 'old_leaderboard'
        }
        /// <summary>
        /// Test the property 'new_leaderboard'
        /// </summary>
        [Test]
        public void new_leaderboardTest()
        {
            // TODO unit test for the property 'new_leaderboard'
        }

    }

}
