/* 
 * SCILL API
 *
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.2.0
 * Contact: support@scillgame.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SCILL.Api;
using SCILL.Model;
using SCILL.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SCILL.Test
{
    /// <summary>
    ///  Class for testing LeaderboardResults
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LeaderboardResultsTests
    {
        // TODO uncomment below to declare an instance variable for LeaderboardResults
        //private LeaderboardResults instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LeaderboardResults
            //instance = new LeaderboardResults();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LeaderboardResults
        /// </summary>
        [Test]
        public void LeaderboardResultsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LeaderboardResults
            //Assert.IsInstanceOfType<LeaderboardResults> (instance, "variable 'instance' is a LeaderboardResults");
        }


        /// <summary>
        /// Test the property 'leaderboard_id'
        /// </summary>
        [Test]
        public void leaderboard_idTest()
        {
            // TODO unit test for the property 'leaderboard_id'
        }
        /// <summary>
        /// Test the property 'leaderboard_name'
        /// </summary>
        [Test]
        public void leaderboard_nameTest()
        {
            // TODO unit test for the property 'leaderboard_name'
        }
        /// <summary>
        /// Test the property 'leaderboard_sort_order_ascending'
        /// </summary>
        [Test]
        public void leaderboard_sort_order_ascendingTest()
        {
            // TODO unit test for the property 'leaderboard_sort_order_ascending'
        }
        /// <summary>
        /// Test the property 'leaderboard_results_by_member_type'
        /// </summary>
        [Test]
        public void leaderboard_results_by_member_typeTest()
        {
            // TODO unit test for the property 'leaderboard_results_by_member_type'
        }

    }

}
