:: Generated by: https://github.com/swagger-api/swagger-codegen.git
::

@echo off

SET CSCPATH=%SYSTEMROOT%\Microsoft.NET\Framework\v4.0.30319

if not exist ".\nuget.exe" powershell -Command "(new-object System.Net.WebClient).DownloadFile('https://dist.nuget.org/win-x86-commandline/latest/nuget.exe', '.\nuget.exe')"
.\nuget.exe install src\SCILL\packages.config -o packages

if not exist ".\bin" mkdir bin

copy packages\Newtonsoft.Json.12.0.2\lib\net45\Newtonsoft.Json.dll bin\Newtonsoft.Json.dll
copy packages\Proyecto26.RestClient.2.6.1\lib\net35\Proyecto26.RestClient.dll bin\Proyecto26.RestClient.dll
copy packages\RSG.Promise.3.0.1\lib\net35\RSG.Promise.dll bin\RSG.Promise.dll
%CSCPATH%\csc  /reference:bin\Newtonsoft.Json.dll;bin\Proyecto26.RestClient.dll;bin\RSG.Promise.dll;System.ComponentModel.DataAnnotations.dll  /target:library /out:bin\SCILL.dll /recurse:src\SCILL\*.cs /doc:bin\SCILL.xml

