/* 
 * SCILL API
 *
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = SCILL.Client.SwaggerDateConverter;

namespace SCILL.Model
{
    /// <summary>
    /// This object is sent via Webhook or notifications of type battlepass-expired.
    /// </summary>
    [DataContract]
        public partial class BattlePassExpiredPayload :  IEquatable<BattlePassExpiredPayload>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BattlePassExpiredPayload" /> class.
        /// </summary>
        /// <param name="webhookType">The type of the notification. If you receive this payload, it&#x27;s most likely battlepass-expired.</param>
        /// <param name="oldBattlePass">oldBattlePass.</param>
        /// <param name="newBattlePass">newBattlePass.</param>
        public BattlePassExpiredPayload(string webhookType = default(string), BattlePassState oldBattlePass = default(BattlePassState), BattlePassState newBattlePass = default(BattlePassState))
        {
            this.webhook_type = webhookType;
            this.old_battle_pass = oldBattlePass;
            this.new_battle_pass = newBattlePass;
        }
        
        /// <summary>
        /// The type of the notification. If you receive this payload, it&#x27;s most likely battlepass-expired
        /// </summary>
        /// <value>The type of the notification. If you receive this payload, it&#x27;s most likely battlepass-expired</value>
        [DataMember(Name="webhook_type", EmitDefaultValue=false)]
        public string webhook_type { get; set; }

        /// <summary>
        /// Gets or Sets old_battle_pass
        /// </summary>
        [DataMember(Name="old_battle_pass", EmitDefaultValue=false)]
        public BattlePassState old_battle_pass { get; set; }

        /// <summary>
        /// Gets or Sets new_battle_pass
        /// </summary>
        [DataMember(Name="new_battle_pass", EmitDefaultValue=false)]
        public BattlePassState new_battle_pass { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BattlePassExpiredPayload {\n");
            sb.Append("  webhook_type: ").Append(webhook_type).Append("\n");
            sb.Append("  old_battle_pass: ").Append(old_battle_pass).Append("\n");
            sb.Append("  new_battle_pass: ").Append(new_battle_pass).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BattlePassExpiredPayload);
        }

        /// <summary>
        /// Returns true if BattlePassExpiredPayload instances are equal
        /// </summary>
        /// <param name="input">Instance of BattlePassExpiredPayload to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BattlePassExpiredPayload input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.webhook_type == input.webhook_type ||
                    (this.webhook_type != null &&
                    this.webhook_type.Equals(input.webhook_type))
                ) && 
                (
                    this.old_battle_pass == input.old_battle_pass ||
                    (this.old_battle_pass != null &&
                    this.old_battle_pass.Equals(input.old_battle_pass))
                ) && 
                (
                    this.new_battle_pass == input.new_battle_pass ||
                    (this.new_battle_pass != null &&
                    this.new_battle_pass.Equals(input.new_battle_pass))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.webhook_type != null)
                    hashCode = hashCode * 59 + this.webhook_type.GetHashCode();
                if (this.old_battle_pass != null)
                    hashCode = hashCode * 59 + this.old_battle_pass.GetHashCode();
                if (this.new_battle_pass != null)
                    hashCode = hashCode * 59 + this.new_battle_pass.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
