/* 
 * SCILL API
 *
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: support@scillgame.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = SCILL.Client.SwaggerDateConverter;

namespace SCILL.Model
{
    /// <summary>
    /// The object containing secondary metadata ranking information, useful for tied scores on the main tracking parameter
    /// </summary>
    [DataContract]
        public partial class LeaderboardMemberMetadata :  IEquatable<LeaderboardMemberMetadata>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LeaderboardMemberMetadata" /> class.
        /// </summary>
        /// <param name="key">The event type key used for ranking.</param>
        /// <param name="ranked">Determines if the user is ranked for that event type key. If false, no score and rank will be provided.</param>
        /// <param name="score">The score achieved as an integer value. If you want to store floats, for example laptimes you need to convert them into an int before (i.e. multiply by 100 to get hundreds of seconds and format back to float in UI).</param>
        /// <param name="rank">The position within the leaderboard.</param>
        public LeaderboardMemberMetadata(string key = default(string), bool? ranked = default(bool?), int? score = default(int?), int? rank = default(int?))
        {
            this.key = key;
            this.ranked = ranked;
            this.score = score;
            this.rank = rank;
        }
        
        /// <summary>
        /// The event type key used for ranking
        /// </summary>
        /// <value>The event type key used for ranking</value>
        [DataMember(Name="key", EmitDefaultValue=false)]
        public string key { get; set; }

        /// <summary>
        /// Determines if the user is ranked for that event type key. If false, no score and rank will be provided
        /// </summary>
        /// <value>Determines if the user is ranked for that event type key. If false, no score and rank will be provided</value>
        [DataMember(Name="ranked", EmitDefaultValue=false)]
        public bool? ranked { get; set; }

        /// <summary>
        /// The score achieved as an integer value. If you want to store floats, for example laptimes you need to convert them into an int before (i.e. multiply by 100 to get hundreds of seconds and format back to float in UI)
        /// </summary>
        /// <value>The score achieved as an integer value. If you want to store floats, for example laptimes you need to convert them into an int before (i.e. multiply by 100 to get hundreds of seconds and format back to float in UI)</value>
        [DataMember(Name="score", EmitDefaultValue=false)]
        public int? score { get; set; }

        /// <summary>
        /// The position within the leaderboard
        /// </summary>
        /// <value>The position within the leaderboard</value>
        [DataMember(Name="rank", EmitDefaultValue=false)]
        public int? rank { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LeaderboardMemberMetadata {\n");
            sb.Append("  key: ").Append(key).Append("\n");
            sb.Append("  ranked: ").Append(ranked).Append("\n");
            sb.Append("  score: ").Append(score).Append("\n");
            sb.Append("  rank: ").Append(rank).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as LeaderboardMemberMetadata);
        }

        /// <summary>
        /// Returns true if LeaderboardMemberMetadata instances are equal
        /// </summary>
        /// <param name="input">Instance of LeaderboardMemberMetadata to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LeaderboardMemberMetadata input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.key == input.key ||
                    (this.key != null &&
                    this.key.Equals(input.key))
                ) && 
                (
                    this.ranked == input.ranked ||
                    (this.ranked != null &&
                    this.ranked.Equals(input.ranked))
                ) && 
                (
                    this.score == input.score ||
                    (this.score != null &&
                    this.score.Equals(input.score))
                ) && 
                (
                    this.rank == input.rank ||
                    (this.rank != null &&
                    this.rank.Equals(input.rank))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.key != null)
                    hashCode = hashCode * 59 + this.key.GetHashCode();
                if (this.ranked != null)
                    hashCode = hashCode * 59 + this.ranked.GetHashCode();
                if (this.score != null)
                    hashCode = hashCode * 59 + this.score.GetHashCode();
                if (this.rank != null)
                    hashCode = hashCode * 59 + this.rank.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
